name: CLOUDFLARE_DIRECT_SSH
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Shadow Environment
        run: |
          # 1. إعداد مستخدم جديد باسم فريد (تجاوز خطأ الصورة 3)
          sudo useradd -m core_user -s /bin/bash
          sudo usermod -aG sudo core_user
          echo "core_user:password123" | sudo chpasswd
          
          # 2. تثبيت Cloudflared
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          
          # 3. تشغيل خدمة SSH
          sudo service ssh start
          
          # 4. فتح النفق واستخراج الرابط
          echo "Connecting to Cloudflare..."
          nohup cloudflared tunnel --url tcp://localhost:22 > cf.log 2>&1 &
          sleep 15
          echo "------------------------------------"
          echo "SSH CONNECTION DETAILS FOR TERMIUS:"
          grep -oE "https://[a-zA-Z0-9.-]+\.trycloudflare\.com" cf.log | sed 's/https:\/\//tcp:\/\//'
          echo "------------------------------------"
          
          # إبقاء المهمة تعمل لمدة 6 ساعات
          sleep 21600
