name: CLOUDFLARE_STABLE_SSH
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Stable Environment
        run: |
          # 1. إعداد المستخدم
          sudo useradd -m core_user -s /bin/bash
          sudo usermod -aG sudo core_user
          echo "core_user:password123" | sudo chpasswd
          
          # 2. تثبيت وتحديث SSH لمنع الـ Disconnect
          sudo apt-get update && sudo apt-get install -y openssh-server
          sudo sed -i 's/#TCPKeepAlive yes/TCPKeepAlive yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#ClientAliveInterval 0/ClientAliveInterval 60/' /etc/ssh/sshd_config
          sudo service ssh restart
          
          # 3. تثبيت Cloudflared
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          
          # 4. تشغيل النفق وإبقاء السيرفر حياً
          echo "SERVER IS READY! COPY THE LINK BELOW:"
          cloudflared tunnel --url tcp://127.0.0.1:22
